backend:
  image: ghcr.io/albertycl/flask-backend
  tag: 9f60d5acb6a9a259752e757c6bb437f81a26677d
  replicas: 2
  port: 5000

frontend:
  image: ghcr.io/albertycl/quasar-frontend
  tag: 9f60d5acb6a9a259752e757c6bb437f81a26677d
  replicas: 2
  port: 80
  host: taskmanager.localhost
  serviceName: quasar-frontend
