apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flask-backend-monitor
  labels:
    app: flask-backend
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: flask-backend
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
