apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
spec:                                           # Deployment spec
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:                                       # Pod spec
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: flask-backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: APP_VERSION
              value: "{{ .Values.backend.tag }}"
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
