apiVersion: apps/v1
kind: Deployment
metadata:
  name: quasar-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: quasar-frontend
  template:
    metadata:
      labels:
        app: quasar-frontend
    spec:
      containers:
        - name: quasar-frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
