apiVersion: apps/v1
kind: Deployment
metadata:
  name: pure-flask
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: pure-flask
  template:
    metadata:
      labels:
        app: pure-flask
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: pure-flask
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
          readinessProbe:
            httpGet:
              path: /api/health
              port: {{ .Values.backend.port }}
